//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingProject.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ServiceReference1", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name carrier from namespace ServiceReference1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="ServiceReference1/CalcTotal", ReplyAction="*")]
        ShippingProject.ServiceReference1.CalcTotalResponse CalcTotal(ShippingProject.ServiceReference1.CalcTotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceReference1/CalcTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<ShippingProject.ServiceReference1.CalcTotalResponse> CalcTotalAsync(ShippingProject.ServiceReference1.CalcTotalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcTotalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcTotal", Namespace="ServiceReference1", Order=0)]
        public ShippingProject.ServiceReference1.CalcTotalRequestBody Body;
        
        public CalcTotalRequest() {
        }
        
        public CalcTotalRequest(ShippingProject.ServiceReference1.CalcTotalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ServiceReference1")]
    public partial class CalcTotalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string carrier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string shippingMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double weight;
        
        public CalcTotalRequestBody() {
        }
        
        public CalcTotalRequestBody(string carrier, string shippingMethod, double weight) {
            this.carrier = carrier;
            this.shippingMethod = shippingMethod;
            this.weight = weight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcTotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcTotalResponse", Namespace="ServiceReference1", Order=0)]
        public ShippingProject.ServiceReference1.CalcTotalResponseBody Body;
        
        public CalcTotalResponse() {
        }
        
        public CalcTotalResponse(ShippingProject.ServiceReference1.CalcTotalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ServiceReference1")]
    public partial class CalcTotalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalcTotalResult;
        
        public CalcTotalResponseBody() {
        }
        
        public CalcTotalResponseBody(double CalcTotalResult) {
            this.CalcTotalResult = CalcTotalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ShippingProject.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ShippingProject.ServiceReference1.WebService1Soap>, ShippingProject.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShippingProject.ServiceReference1.CalcTotalResponse ShippingProject.ServiceReference1.WebService1Soap.CalcTotal(ShippingProject.ServiceReference1.CalcTotalRequest request) {
            return base.Channel.CalcTotal(request);
        }
        
        public double CalcTotal(string carrier, string shippingMethod, double weight) {
            ShippingProject.ServiceReference1.CalcTotalRequest inValue = new ShippingProject.ServiceReference1.CalcTotalRequest();
            inValue.Body = new ShippingProject.ServiceReference1.CalcTotalRequestBody();
            inValue.Body.carrier = carrier;
            inValue.Body.shippingMethod = shippingMethod;
            inValue.Body.weight = weight;
            ShippingProject.ServiceReference1.CalcTotalResponse retVal = ((ShippingProject.ServiceReference1.WebService1Soap)(this)).CalcTotal(inValue);
            return retVal.Body.CalcTotalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShippingProject.ServiceReference1.CalcTotalResponse> ShippingProject.ServiceReference1.WebService1Soap.CalcTotalAsync(ShippingProject.ServiceReference1.CalcTotalRequest request) {
            return base.Channel.CalcTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShippingProject.ServiceReference1.CalcTotalResponse> CalcTotalAsync(string carrier, string shippingMethod, double weight) {
            ShippingProject.ServiceReference1.CalcTotalRequest inValue = new ShippingProject.ServiceReference1.CalcTotalRequest();
            inValue.Body = new ShippingProject.ServiceReference1.CalcTotalRequestBody();
            inValue.Body.carrier = carrier;
            inValue.Body.shippingMethod = shippingMethod;
            inValue.Body.weight = weight;
            return ((ShippingProject.ServiceReference1.WebService1Soap)(this)).CalcTotalAsync(inValue);
        }
    }
}
